#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times with while
i=0
while ((i < 10)); do
    echo "Holberton School"
    if ((i == 8)); then
        echo "Hi"
    fi
    let i+=1
done
