#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times with while
i=0
while ((i < 10)); do
    if ((i == 7)); then
        echo "good luck"
    elif ((i == 3)); then
        echo "bad luck"
    else
        echo "Holberton School"
    fi
    let i+=1
done
