#!/usr/bin/env bash
# This script is displaying the numbers until 20 with while
i=1
while ((i < 21)); do
    echo $i
    case $i in
        4)
        echo "bad luck from China";;
        9)
        echo "bad luck from Japan";;
        17)
        echo "bad luck from Italy";;
    esac
    let i+=1
done
